id: P6540C115
initial_creation_type: ocr
source_metadata:
  volumes:
    31c63a34c9b844088220aefe64d22b6d:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རྡོ་རྗེ་སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
