id: P6540C115
initial_creation_type: ocr
source_metadata:
  volumes:
    036e16f0072e4082b749690bdd07d5eb:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རྡོ་རྗེ་སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
